version: '3.7'

services:
  drupal:
    image: drupal:latest
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=endrik    # Kasutajanimi "endrik"
      - DRUPAL_DB_PASSWORD=123   # Parool "123"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: endrik       # Kasutajanimi "endrik"
      MYSQL_PASSWORD: 123      # Parool "123"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=endrik        # Kasutajanimi "endrik"
      - PMA_PASSWORD=123       # Parool "123"
    depends_on:
      - db

volumes:
  drupal_data:
  db_data:

